### ISSUE TITLE
makeAddListener breaks when the Event Name is a Symbol

### ISSUE THREAD

**Issue by jreidgreer** [angular/zone.js#1110]
When Zone.js is running in Node, it appears to be wrapping Node's EventEmitter methods, causing issues when the `eventName` is a Symbol. Node's [documentation states that `eventName` can be a string or a symbol.](https://nodejs.org/api/events.html#events_emitter_on_eventname_listener)

However, Zone tries to coerce `eventName` into a string:

https://github.com/angular/zone.js/blob/e9536ec7d724e21473496c090378d6635944c798/lib/common/events.ts#L383

This causes an error:

```
TypeError: Cannot convert a Symbol value to a string
    at Unpack.<anonymous> (zone.js/dist/zone-node.js:1688:52)
    at new Parser (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/parse.js:70:12)
    at new <anonymous> (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/warn-mixin.js:2:26)
    at new Unpack (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/unpack.js:52:5)
    at extract (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/extract.js:111:10)
    at Object.module.exports (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/extract.js:38:7)
    at extractStream (/gulp-custom-plugin/node_modules/custom-module/node_modules/pacote/lib/extract-stream.js:39:1
```

This is causing an issue in the `node-tar` library, [for instance](https://github.com/npm/node-tar/issues/189).

**Comment by JiaLiPassion** [comment]
@jreidgreer , thank you for posting the issue, I will fix this one.

**Comment by Mathyn** [comment]
Is a fix already available? I am also running into issues using node-tar with zone.js. I use zone.js version 0.8.26.

**Comment by alamothe** [comment]
Running into this issue after upgrading Node, is there a fix?

**Comment by JiaLiPassion** [comment]
@alamothe, it is fixed, but not merged yet, please wait for the next release(not sure when...)

**Comment by jreidgreer** [comment]
@Mathyn @alamothe you can prevent this issue if you place this before Zone bootstraps:

```js
global.__Zone_disable_EventEmitter = true;
```

Obviously not idea, but it'll do the trick.

**Comment by alamothe** [comment]
Does it have any side-effect...?

**Comment by JiaLiPassion** [comment]
@alamothe, the `side-effect` will be the `callback` of `addListener(eventName, callback)` will not under the control of `zone.js`, so it will outside of `zone`. if you are working on something relying on it (such as `Change detection` in Electron), it will not work.

**Comment by alamothe** [comment]
No worries, in my case I'm fine with `puppeteer` 1.8 for now and will wait for the next release. Thanks!
