### ISSUE TITLE
Zone.js does not work with Zombie/jsdom

### ISSUE THREAD

**Issue by mhevery** [angular/zone.js#156]
I'm trying to get an Angular2 app running in Zombie, and seeing the following error (presumably from jsdom):

TypeError: Cannot redefine property: onclick
    at Function.defineProperty (native)
    at canPatchViaPropertyDescriptor (http://localhost:8080/app.js:35698:12)
    at Object.apply (http://localhost:8080/app.js:35677:9)
    at Object.apply (http://localhost:8080/app.js:35288:29)
    at http://localhost:8080/app.js:35165:16
    at linkDynamicModule (http://localhost:8080/app.js:262:32)
    at getModule (http://localhost:8080/app.js:231:9)
    at http://localhost:8080/app.js:266:16
    at http://localhost:8080/app.js:35147:20
    at linkDynamicModule (http://localhost:8080/app.js:262:32)
    in http://localhost:8080/

ORIGINALY FILED AS: https://github.com/angular/angular/issues/3584

**Comment by btford** [comment]
Looks like we need to wrap that check in a try/catch for environments that make that property non-configurable.

**Comment by danhalliday** [comment]
I might be able to spend some time looking at a PR, as it'd be really cool to try out Zombie with Angular 2. When you say try/catch it, do you mean just fail more gracefully, or do you think it would be possible for Zone to work without redefining `onclick`?

**Comment by danhalliday** [comment]
What's strange is that looking at the code, it seems Zone already handles non-configurable properties (here: https://github.com/angular/zone.js/blob/f8a2be5ab889b3026774ea36cea4e385399a52df/lib/patch/property-descriptor.js#L36 it looks like `patchViaCapturingAllTheEvents()` should be called).

**Comment by danhalliday** [comment]
I've debugged my app code and tracked down the actual stack trace for the error:

    Object.defineProperty(obj, prop, desc); (https://github.com/angular/zone.js/blob/master/lib/utils.js#L73)
    patchProperty(obj, eventName); (https://github.com/angular/zone.js/blob/master/lib/utils.js#L88)
    utils.patchProperties(HTMLElement.prototype, onEventNames); (https://github.com/angular/zone.js/blob/master/lib/patch/property-descriptor.js#L21)
    propertyDescriptorPatch.apply(); (https://github.com/angular/zone.js/blob/master/lib/patch/browser.js#L34)
    browserPatch.apply(); (https://github.com/angular/zone.js/blob/master/lib/browser/zone.js#L13)

Turns out `canPatchViaPropertyDescriptor()` returns `true`.

**Comment by natewallace** [comment]
I was getting this error when trying to run Angular2 with jsdom@7.2.2.  However after upgrading to jsdom@8.0.4 and the latest version of Angular2 and it's dependencies I no longer get this error and I'm able to run Angular2 in jsdom.

**Comment by bvkimball** [comment]
@natewallace does this still work for you?  jsdom@8.5.0 is throwing this issue for me still with angular2

**Comment by natewallace** [comment]
@bvkimball Yes, it still works for me with jsdom@8.5.0, angular2@2.0.0-beta.17, and zone.js@0.6.12.

**Comment by kanipowa** [comment]
With `zone.js@0.6.12` and `angular2@2.0.0-rc.4` `jsdom@9.4.1` fails for me.

**Comment by berwyn** [comment]
Is there any momentum on this? `zone.js@0.7.2`, `@angular/*@2.1.4` and `jsdom@9.8.3` fails when running tests via jest and I'd like to avoid rewriting my existing suite if at all possible

**Comment by mhevery** [comment]
Would love to have A PR for this.

**Comment by Swiip** [comment]
I tried to write a patch for jsdom some times ago and it could work but I don't have the skills to make  a real PR of it: https://github.com/tmpvar/jsdom/pull/1610

**Comment by JiaLiPassion** [comment]
Is there a repo to reproduce? I run the angular2 in zombie simply get a error 'TypeError: Parameter "url" must be a string, not object'
