### ISSUE TITLE
TypeError: Cannot read property '_bound' of undefined

### ISSUE THREAD

**Issue by irthos** [angular/zone.js#21]
Here's the trace:

TypeError: Cannot read property '_bound' of undefined
    at HTMLButtonElement.obj.removeEventListener (http://localhost:9001/bower_components/zone/zone.js:296:19)
    at http://localhost:9001/bower_components/angular/angular.js:2274:46
    at http://localhost:9001/bower_components/angular/angular.js:2429:9
    at Array.forEach (native)
    at forEach (http://localhost:9001/bower_components/angular/angular.js:320:11)
    at jqLiteOff (http://localhost:9001/bower_components/angular/angular.js:2427:5)
    at Object.JQLite.(anonymous function) (http://localhost:9001/bower_components/angular/angular.js:3099:17)
    at Object.fn (http://localhost:9001/app/directives/helper.js:133:29)
    at Scope.$digest (http://localhost:9001/bower_components/angular/angular.js:12533:29)
    at Scope.$apply (http://localhost:9001/bower_components/angular/angular.js:12798:24)

**Comment by vicb** [comment]
@irthos I'm closing this issue as we can not reproduce it. Feel free to re-open if you can add more information.

**Comment by irthos** [comment]
Sorry to forget about this. We were not able to repro this again either. Thanks.
