### ISSUE TITLE
ZoneTask.toString() method missing

### ISSUE THREAD

**Issue by char0n** [angular/zone.js#341]
I have reported this issue to AngularJs team: https://github.com/angular/angular.js/issues/14548

Basically their are right in their assumption that using zone.js should not change setTimeout. Imagine this situation when using zone.js.

```javascript
var deferredTracker = {}

var timerId1 = setTimeout(function() {});
var timerId2 = setTimeout(function() {});

deferredTracker[timerId1] = new Promise(....);
defferedTracker[timerId2] = new Promise(....);
```

The result of defferedTracker is:

```javascript
{"[object Object]": promiseInstance}
```

This is the way angular1 tracks timeouts and interval. Using zone.js allows to cancel only the last timeout or interval.

To fix this issue I would suggest for ZoneTask to have toString method which for setTimeout and setInterval should look like this:

```javascript
toString: function() {
  return this.data.handleId;
} 
```

Without fixing this, using zone.js in angular1 application is just not possible.

Thank you

**Comment by char0n** [comment]
I have created modified distribution file here: http://filebin.ca/2hRxo13INo5U/zone.js-0.6.12.tgz

Affected files are:
- dist/zone.js
- dist/zone-node.js

Both file have toString method implemented. Using this file is the only way to use zone.js along with angular 1.5 side by side.

**Comment by mhevery** [comment]
@char0n Nice catch. Could you create PR with a fix?

**Comment by char0n** [comment]
@mhevery I'll try

**Comment by char0n** [comment]
I am having problem installing the project. I run on Windows 8.1. In order to install the project I had to modify the package.json:

```javascript
"prepublish": "./node_modules/.bin/typings install && ./node_modules/.bin/tsc && gulp build"
```
to 
```javascript
"prepublish": "./node_modules/.bin/typings install && call ./node_modules/.bin/tsc && gulp build"
```

Then when I run npm install I get this error:

```
> zone.js@0.6.12 prepublish C:\Users\char0n\Documents\GitHub\zone.js
> typings install && call ./node_modules/.bin/tsc && gulp build


├── es6-promise (ambient)
├── node (ambient)
└── jasmine (ambient dev)

[10:30:27] Using gulpfile ~\Documents\GitHub\zone.js\gulpfile.js
[10:30:27] Starting 'build/zone.js'...
[10:30:28] Starting 'compile'...
[10:30:28] Starting 'build/zone.min.js'...
[10:30:28] Starting 'build/zone-node.js'...
[10:30:28] Starting 'build/jasmine-patch.js'...
[10:30:28] Starting 'build/jasmine-patch.min.js'...
[10:30:28] Starting 'build/long-stack-trace-zone.js'...
[10:30:28] Starting 'build/long-stack-trace-zone.min.js'...
[10:30:28] Starting 'build/wtf.js'...
[10:30:28] Starting 'build/wtf.min.js'...
[10:30:28] Starting 'build/async-test.js'...
[10:30:28] Starting 'build/fake-async-test.js'...
[10:30:28] Starting 'build/sync-test.js'...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./node_modules/.bin/tsc ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3

npm verb lifecycle zone.js@0.6.12~prepublish: unsafe-perm in lifecycle true
npm verb lifecycle zone.js@0.6.12~prepublish: 
```

Here is full npm-debug.log: https://gist.github.com/char0n/ac5d88b2067f715d4320998292d1de32

**Comment by jahtalab** [comment]
Is there a way to keep the native behaviour of `setTimeout`, i.e. returning a numerical ID of the timeout?

**Comment by jahtalab** [comment]
related: #360

**Comment by henrysun918** [comment]
after updating to rc.3, I can't repro #361 anymore.
