### ISSUE TITLE
Breaks Intl API in older versions of Chrome

### ISSUE THREAD

**Issue by mlaval** [angular/zone.js#391]
In an Android 4.4 emulator for example, when zone.js is loaded, executing `new Intl.NumberFormat().format(36000)` raises the following error: `TypeError: Cannot redefine property: length`

The reason behind it some V8 code which freezes an array of locales after initialising it:
https://github.com/v8/v8/blob/d93fd41aaa0982ae8c4226cce3f2629649ebe87a/src/js/i18n.js#L577
With the new `Object.defineProperty` from zone.js, it fails because it actually executes something like:
`Object.defineProperty([], 'length', {value: 0, writable: false, configurable: true})`
which fails in any version of Chrome.

Apparently, in recent version of Chrome, it seems that the list of locales is initialised only once, before zone.js is loaded. So there is no issue.

But in older version, the initialisation is done each time `new Intl.NumberFormat()` or `Intl.DateFormat()` are called, hence the problem.

The issue was reported in angular/angular#8188 and can also be seen when running Angular's Intl unit tests in these browsers.

**Comment by mlaval** [comment]
Also breaks `Sting.localeCompare()` in the same browser, see https://github.com/angular/angular/issues/10589

**Comment by mhevery** [comment]
This is surprising as we do not do anything with Intl API. Could you narrow it further?

**Comment by yusufbata** [comment]
Stack trace with error:

ORIGINAL EXCEPTION: TypeError: Cannot redefine property: length
ORIGINAL STACKTRACE:
TypeError: Cannot redefine property: length
    at defineProperty (native)
    at Function.Object.defineProperty (file:///android_asset/www/build/js/zone.js:1035:17)
    at freezeArray (v8/i18n:2004:8)
    at initializeLocaleList (v8/i18n:286:8)
    at resolveLocale (v8/i18n:1812:4)
    at initializeDateTimeFormat (v8/i18n:1149:7)
    at new Object.defineProperty.value.ax (v8/i18n:1227:8)
    at Object.yMMMd (file:///android_asset/www/build/js/app.bundle.js:2229:16)
    at dateFormatter (file:///android_asset/www/build/js/app.bundle.js:2239:39)
    at Function.DateFormatter.format (file:///android_asset/www/build/js/app.bundle.js:2274:16)
