### ISSUE TITLE
0.6.13 - TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by CrisGrec** [angular/zone.js#399]
Since updating from `0.6.12` to `0.6.13` I get the following stacktrace when using `fakeAsync` in my tests:

```
TypeError: Cannot read property 'length' of undefined
    at flushErrors (dist/vendor/zone.js/dist/fake-async-test.js:227:79)
    at FakeAsyncTestZoneSpec.flushMicrotasks (dist/vendor/zone.js/dist/fake-async-test.js:236:14)
    at flushMicrotasks (dist/vendor/@angular/core/testing/fake_async.js:97:29)
    at eval (dist/vendor/@angular/core/testing/fake_async.js:42:13)
    at ZoneDelegate.invoke (dist/vendor/zone.js/dist/zone.js:332:29)
    at Zone.run (dist/vendor/zone.js/dist/zone.js:225:44)
    at Object.eval (dist/vendor/@angular/core/testing/fake_async.js:40:33)
```

Example usage of `fakeAsync` in our tests:

```
it('...',
  fakeAsync(inject([WebSocketService, ExtractorService],
    (webSocketService: WebSocketService, extractorService: ExtractorService) => {
      tick(1000);
      expect(extractorService.getStatus()).toBe(ExtractorStatus.DISCONNECTED);
      discardPeriodicTasks();
  }))
);
```

Rolling back to `0.6.12` for now.

**Comment by tflori** [comment]
I get the same error maybe it is the same row:
```js
if (_this._lastError !== null || _this._uncaughtPromiseErrors.length) {
    // If there is an error stop processing the microtask queue and rethrow the error.
    _this._resetLastErrorAndThrow();
}
```

The problem here is that `_uncaughtPromiseErrors` get initialized this way:
`this._uncaughtPromiseErrors = Promise[Zone['__symbol__']('uncaughtPromiseErrors')]`

So it can be undefined.

I will create a pull request for it.

**Comment by tflori** [comment]
I created a pull request that solves the problem in my case:
https://github.com/angular/zone.js/pull/479

**Comment by JiaLiPassion** [comment]
close for fixed.
