### ISSUE TITLE
bug: Zone.js error with mongoosedb(Angular2 Universal), old version works

### ISSUE THREAD

**Issue by medozs** [angular/zone.js#453]
When I use the new Zone.js and connect mongodb to my app, it causes an error. 
When I use the old Zone.js, the database is connected successfully. works (but cause other problems with Angular2).

The error that is caused by the new Zone.js is:
TypeError: Cannot read property 'filter' of undefined
at zoneAwareEventListeners (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:715:13)
at Db.listeners (eval at createNamedFn (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:724:17), :3:36)
at Server.listener (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\mongodb\lib\db.js:1786:15)
at Server.g (events.js:286:16)
at ZoneDelegate.invokeTask (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:225:37)
at Zone.runTask (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:125:47)
at Server.ZoneTask.invoke (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:293:33)
at emitTwo (events.js:106:13)
at Server.emit (events.js:191:7)
at Server.connectHandler (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\mongodb\lib\server.js:329:10)
at Server.g (events.js:286:16)
at ZoneDelegate.invokeTask (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:225:37)
at Zone.runTask (c:\Users\ahmed\Documents\Me\Projects\Netbine5\node_modules\zone.js\dist\zone-node.js:125:47)
at Server.ZoneTask.invoke 

Please help.

Thank You,

**Comment by medozs** [comment]
I fixed the issue, I found that this version of the file zone-node.js committed 7 days ago (after replacing the current one with it) worked well without any errors for my app.

**Comment by jvbianchi** [comment]
it may be related with https://github.com/angular/zone.js/issues/448

**Comment by KrauseStefan** [comment]
Hi

I had some similar errors previously could you maybe check if your issue is resolved?
The PR that fixed the issue is #475.

you need to build it in order to test it.

I've tried to create an unofficial release that you can test with [here](https://github.com/KrauseStefan/zone.js/releases/download/v0.6.27/zone.js.zip)

If it works then we might be able to get the team to cut a official release.
