### ISSUE TITLE
Zone.js 0.6.22 and higher causes errors in Hapi 14 and lower

### ISSUE THREAD

**Issue by bisubus** [angular/zone.js#487]
The problem is common to Zone.js 0.6.22 and higher (up to 0.6.25 atm) and all major Hapi versions from 8 to 14. Hapi 15 doesn't have this problem.

Any request to Hapi server causes this error:

```
TypeError: Cannot read property 'filter' of undefined
    at zoneAwareEventListeners (<...>\node_modules\zone.js\dist\zone-node.js:707:13)
    at listeners (eval at createNamedFn (<...>\node_modules\zone.js\dist\zone-node.js:716:17), <anonymous>:3:36)
    at internals.Response._tap (<...>\node_modules\hapi\lib\response.js:599:18)
    at Object.internals.transmit (<...>\node_modules\hapi\lib\transmit.js:300:26)
    at internals.marshal (<...>\node_modules\hapi\lib\transmit.js:37:26)
    at Function.internals.Auth.response (<...>\node_modules\hapi\lib\auth.js:267:16)
    at response._marshal (<...>\node_modules\hapi\lib\transmit.js:106:25)
    at internals.Response._streamify (<...>\node_modules\hapi\lib\response.js:593:12)
    at internals.Response._marshal (<...>\node_modules\hapi\lib\response.js:534:21)
    at internals.state (<...>\node_modules\hapi\lib\transmit.js:85:18)
```

[Here's a repo](https://github.com/bisubus/unhapi-test-zone) that demonstrates the issue.

**Comment by JiaLiPassion** [comment]
This has been fixed by this commit https://github.com/angular/zone.js/commit/431f6f07f0659055d692828fd0ba84cde078e2fb, you 
can update to 0.6.26 to resolve this issue.

**Comment by bisubus** [comment]
@JiaLiPassion It was fixed indeed, thanks.
