### ISSUE TITLE
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten

### ISSUE THREAD

**Issue by bdunn44** [angular/zone.js#501]
Using:
- Angular 2.1.0
- Zone.js 0.6.26
- Angular Universal 2.1.0-rc.1
- Webpack 2.1.0-beta.25

I'm receiving the following error from `Zone.assertZonePatched()`:

`Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten`

I referred to Angular issue [#11650](https://github.com/angular/angular/issues/11650), but I get this error regardless of how late I import Zone.js, **or if I remove the import altogether**. I'm not using Bing as mentioned in #465 and I've checked all of the SO answers as well.

I've manually checked that `window.Promise` does in fact look to be patched (using `toString`, `JSON.stringify`, and the helper method [here](http://stackoverflow.com/a/1144249)), so only thing I can think of is that Zone is being loaded twice, but should't [this](https://github.com/angular/zone.js/blob/master/lib/zone.ts#L529) catch that?

To workaround the issue I've added a very hacky line of code to [assertZonePatched](https://github.com/angular/zone.js/blob/master/lib/zone.ts#L535) to just re-patch the thing:

```
    static assertZonePatched() {
      window.Promise = ZoneAwarePromise;
      ...
    }
```

Everything seems to work correctly, but I'm thinking this probably isn't stable, otherwise you guys would have patched `window.Promise` at that point in the lifecycle to begin with. Any guidance would be appreciated.

**Comment by bdunn44** [comment]
Forgot to mention, I also added a log statement [here](https://github.com/angular/zone.js/blob/master/lib/zone.ts#L1196) and it's only executed once.

**Comment by bdunn44** [comment]
Found the issue to be:

```
import 'core-js/es6';
```

Removing this import resolved the issue.

**Comment by smartHasmukh** [comment]
@bdunn44 I am facing below issue. but I haven't idea how can I solved that issue.

(program):8 Unhandled promise rejection ZoneAwareError__zone_symbol__error: Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at new Error (native)
    at Function.webpackJsonp.556.Zone.assertZonePatched (http://localhost:4200/polyfills.bundle.js:5344:23) [<root>]
    at new NgZone (http://localhost:4200/vendor.bundle.js:40028:14) [<root>]
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:4200/vendor.bundle.js:51772:22) [<root>]
    at http://localhost:4200/vendor.bundle.js:51826:59 [<root>]
    at g (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:10016) [<root>]
    at eval (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:10138) [<root>]
    at MutationObserver.k (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:14293) [<root>]
    at Zone.webpackJsonp.556.Zone.runGuarded (http://localhost:4200/polyfills.bundle.js:5443:47) [<root> => <root>]
    at MutationObserver.<anonymous> (http://localhost:4200/polyfills.bundle.js:5421:29) [<root>]message: "Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.↵Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)"originalStack: "Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.↵Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)↵    at new Error (native)↵    at Error.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:6262:33)↵    at Function.webpackJsonp.556.Zone.assertZonePatched (http://localhost:4200/polyfills.bundle.js:5344:23)↵    at new NgZone (http://localhost:4200/vendor.bundle.js:40028:14)↵    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:4200/vendor.bundle.js:51772:22)↵    at http://localhost:4200/vendor.bundle.js:51826:59↵    at g (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:10016)↵    at eval (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:10138)↵    at MutationObserver.k (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:14293)↵    at ZoneDelegate.webpackJsonp.556.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:5634:26)↵    at Zone.webpackJsonp.556.Zone.runGuarded (http://localhost:4200/polyfills.bundle.js:5443:47)↵    at MutationObserver.<anonymous> (http://localhost:4200/polyfills.bundle.js:5421:29)"stack: (...)get stack: stack()set stack: stack()zoneAwareStack: "Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.↵Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)↵    at new Error (native)↵    at Function.webpackJsonp.556.Zone.assertZonePatched (http://localhost:4200/polyfills.bundle.js:5344:23) [<root>]↵    at new NgZone (http://localhost:4200/vendor.bundle.js:40028:14) [<root>]↵    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:4200/vendor.bundle.js:51772:22) [<root>]↵    at http://localhost:4200/vendor.bundle.js:51826:59 [<root>]↵    at g (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:10016) [<root>]↵    at eval (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:10138) [<root>]↵    at MutationObserver.k (eval at <anonymous> (http://localhost:4200/scripts.bundle.js:53:8), <anonymous>:8:14293) [<root>]↵    at Zone.webpackJsonp.556.Zone.runGuarded (http://localhost:4200/polyfills.bundle.js:5443:47) [<root> => <root>]↵    at MutationObserver.<anonymous> (http://localhost:4200/polyfills.bundle.js:5421:29) [<root>]"__proto__: Objectmessage: (...)get message: ()set message: (value)name: (...)get name: ()set name: (value)originalStack: (...)get originalStack: ()set originalStack: (value)stack: (...)get stack: ()set stack: (value)toSource: ()toString: ()zoneAwareStack: (...)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: Object(anonymous function) @ (program):8
