### ISSUE TITLE
IE11 Unhandled Promise rejection: BrowserPlatformLocation.prototype.replaceState 

### ISSUE THREAD

**Issue by tsukhu** [angular/zone.js#502]
Hi,
  I am using version 0.6.25 and get this error in IE11 .. This works just fine on Chrome

Any help will be greatly appreciated

Given below is the console log..
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
EXCEPTION: Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (http://localhost:3000/vendor.bundle.js:45136:13)
   at HashLocationStrategy.prototype.replaceState (http://localhost:3000/vendor.bundle.js:2521:9)
   at Location.prototype.replaceState (http://localhost:3000/vendor.bundle.js:2653:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:50381:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at onInvoke (http://localhost:3000/vendor.bundle.js:35731:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at Zone.prototype.run (http://localhost:3000/polyfills.bundle.js:15189:17)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15577:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (http://localhost:3000/vendor.bundle.js:45136:13)
   at HashLocationStrategy.prototype.replaceState (http://localhost:3000/vendor.bundle.js:2521:9)
   at Location.prototype.replaceState (http://localhost:3000/vendor.bundle.js:2653:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:50381:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at onInvoke (http://localhost:3000/vendor.bundle.js:35731:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at Zone.prototype.run (http://localhost:3000/polyfills.bundle.js:15189:17)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15577:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
   at resolvePromise (http://localhost:3000/polyfills.bundle.js:15543:25)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15580:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
  -------------   Elapsed: 76 ms; At: Fri Nov 11 2016 14:29:44 GMT+0530 (India Standard Time)   -------------  
   at Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost:3000/polyfills.bundle.js:14994:9)
   at ZoneDelegate.prototype.scheduleTask (http://localhost:3000/polyfills.bundle.js:15317:21)
   at Zone.prototype.scheduleMicroTask (http://localhost:3000/polyfills.bundle.js:15243:13)
   at scheduleResolveOrReject (http://localhost:3000/polyfills.bundle.js:15575:9)
   at ZoneAwarePromise.prototype.then (http://localhost:3000/polyfills.bundle.js:15661:17)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:50333:13)
   at ZoneAwarePromise (http://localhost:3000/polyfills.bundle.js:15593:29)
   at Router.prototype.runNavigate (http://localhost:3000/vendor.bundle.js:50299:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:50290:54)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at onInvoke (http://localhost:3000/vendor.bundle.js:35731:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at Zone.prototype.run (http://localhost:3000/polyfills.bundle.js:15189:17)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15577:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
  -------------   Elapsed: 1733 ms; At: Fri Nov 11 2016 14:29:42 GMT+0530 (India Standard Time)   -------------  
   at Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost:3000/polyfills.bundle.js:14994:9)
   at ZoneDelegate.prototype.scheduleTask (http://localhost:3000/polyfills.bundle.js:15317:21)
   at Zone.prototype.scheduleMicroTask (http://localhost:3000/polyfills.bundle.js:15243:13)
   at scheduleResolveOrReject (http://localhost:3000/polyfills.bundle.js:15575:9)
   at ZoneAwarePromise.prototype.then (http://localhost:3000/polyfills.bundle.js:15661:17)
   at Router.prototype.scheduleNavigation (http://localhost:3000/vendor.bundle.js:50290:9)
   at Router.prototype.navigateByUrl (http://localhost:3000/vendor.bundle.js:50238:13)
   at Router.prototype.initialNavigation (http://localhost:3000/vendor.bundle.js:50095:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:51051:13)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:26206:49)
   at ApplicationRef_.prototype._loadComponent (http://localhost:3000/vendor.bundle.js:26206:9)
   at ApplicationRef_.prototype.bootstrap (http://localhost:3000/vendor.bundle.js:26192:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:26094:75)
   at PlatformRef_.prototype._moduleDoBootstrap (http://localhost:3000/vendor.bundle.js:26094:13)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:26062:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at onInvoke (http://localhost:3000/vendor.bundle.js:35731:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at Zone.prototype.run (http://localhost:3000/polyfills.bundle.js:15189:17)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15577:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
  -------------   Elapsed: 466 ms; At: Fri Nov 11 2016 14:29:42 GMT+0530 (India Standard Time)   -------------  
   at Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost:3000/polyfills.bundle.js:14994:9)
   at ZoneDelegate.prototype.scheduleTask (http://localhost:3000/polyfills.bundle.js:15317:21)
   at Zone.prototype.scheduleMicroTask (http://localhost:3000/polyfills.bundle.js:15243:13)
   at scheduleResolveOrReject (http://localhost:3000/polyfills.bundle.js:15575:9)
   at resolvePromise (http://localhost:3000/polyfills.bundle.js:15538:21)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15577:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
  -------------   Elapsed: 9 ms; At: Fri Nov 11 2016 14:29:42 GMT+0530 (India Standard Time)   -------------  
   at Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost:3000/polyfills.bundle.js:14994:9)
   at ZoneDelegate.prototype.scheduleTask (http://localhost:3000/polyfills.bundle.js:15317:21)
   at Zone.prototype.scheduleMicroTask (http://localhost:3000/polyfills.bundle.js:15243:13)
   at scheduleResolveOrReject (http://localhost:3000/polyfills.bundle.js:15575:9)
   at ZoneAwarePromise.prototype.then (http://localhost:3000/polyfills.bundle.js:15661:17)
   at ApplicationInitStatus (http://localhost:3000/vendor.bundle.js:25661:9)
   at AppModuleInjector.prototype.createInternal (Function code:245:3)
   at NgModuleInjector.prototype.create (http://localhost:3000/vendor.bundle.js:32123:55)
   at NgModuleFactory.prototype.create (http://localhost:3000/vendor.bundle.js:32108:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:26052:13)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at onInvoke (http://localhost:3000/vendor.bundle.js:35731:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at Zone.prototype.run (http://localhost:3000/polyfills.bundle.js:15189:17)
   at NgZone.prototype.run (http://localhost:3000/vendor.bundle.js:35621:44)
   at PlatformRef_.prototype._bootstrapModuleFactoryWithZone (http://localhost:3000/vendor.bundle.js:26050:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:26089:46)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at Zone.prototype.run (http://localhost:3000/polyfills.bundle.js:15189:17)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15577:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
Unhandled Promise rejection: Unspecified error. ; Zone: angular ; Task: Promise.then ; Value: Error: Unspecified error. Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (http://localhost:3000/vendor.bundle.js:45136:13)
   at HashLocationStrategy.prototype.replaceState (http://localhost:3000/vendor.bundle.js:2521:9)
   at Location.prototype.replaceState (http://localhost:3000/vendor.bundle.js:2653:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:50381:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at onInvoke (http://localhost:3000/vendor.bundle.js:35731:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at Zone.prototype.run (http://localhost:3000/polyfills.bundle.js:15189:17)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15577:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
Error: Uncaught (in promise): Error: Unspecified error.
Error: Unspecified error.
   at BrowserPlatformLocation.prototype.replaceState (http://localhost:3000/vendor.bundle.js:45136:13)
   at HashLocationStrategy.prototype.replaceState (http://localhost:3000/vendor.bundle.js:2521:9)
   at Location.prototype.replaceState (http://localhost:3000/vendor.bundle.js:2653:9)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:50381:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at onInvoke (http://localhost:3000/vendor.bundle.js:35731:21)
   at ZoneDelegate.prototype.invoke (http://localhost:3000/polyfills.bundle.js:15305:13)
   at Zone.prototype.run (http://localhost:3000/polyfills.bundle.js:15189:17)
   at Anonymous function (http://localhost:3000/polyfills.bundle.js:15577:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at onInvokeTask (http://localhost:3000/vendor.bundle.js:35722:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/polyfills.bundle.js:15338:17)
   at Zone.prototype.runTask (http://localhost:3000/polyfills.bundle.js:15229:21)
   at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15476:25)
   at invoke (http://localhost:3000/polyfills.bundle.js:15414:25)
SCRIPT5007: Object expected
File: polyfills.bundle.js, Line: 15233, Column: 25
SCRIPT5007: Object expected
File: polyfills.bundle.js, Line: 15233, Column: 25

**Comment by rihabesx** [comment]
@tsukhu getting the same error on ie11.
Did you find a solution for this?

**Comment by tsukhu** [comment]
@rihabesx yes - it turned out to be related to the index.html where the webpack-dev-server.js needed to be loaded in the end .. I had added some other js files after it. I moved this to the end and it resolved the issue (BTW: I am using a fork of the AngularClass webpack starter project)
 <% if (htmlWebpackPlugin.options.metadata.isDevServer && htmlWebpackPlugin.options.metadata.HMR !== true) { %>
  
  <script src="/webpack-dev-server.js"></script>
  <% } %>

**Comment by Tohnmeister** [comment]
Hmmm. Curious as to why that fixed the issue for you. I'm using a project created with angular-cli and am having the exact same issue. Not using webpack though.

**Comment by Tohnmeister** [comment]
In my case I pinpointed the problem to a native call to `window.history.replaceState`. Actually the error could be reproduced by typing `window.history.replaceState(null, '', 'foo');` in the console of IE11.

After a lot of searching I found that this was caused by a registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Restrictions\NoNavButtons` which was set to 1. Setting it to 0 or entirely deleting the key, resolved the issue.

**Comment by prasadmamidi7** [comment]
Hi

Are you able to resolve the issue without setting the registry entry to 1. In my case i have no control on this registry entry.

**Comment by tsukhu** [comment]
It's been a year since I last last faced this issue. No more now. I guess the best way is to just use the cli generated version of  all the libraries including zone.js and just enable the required polyfills for IE as recommended in the generated polyfills.ts

**Comment by AKlaus** [comment]
Perhaps, I have experienced a relevant problem - Angular authentication form gets open by MS Office apps to authenticate for opening a document (as a part of MS-OFBA authentication for WebDAV protocol). 

The problem is that MS Office opens the page in the [WebBrowser](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752040) control without the toolbar and navigation buttons and disabled right-click. I believe it causes the error with the following call stack:

> EXCEPTION: Uncaught (in promise): Error: Unspecified error.
> Error: Unspecified error.
> at BrowserPlatformLocation.prototype.replaceState (./vendor.bundle.js)
> at PathLocationStrategy.prototype.replaceState (./vendor.bundle.js)
> at Location.prototype.replaceState (./vendor.bundle.js)
> at Router.prototype.resetUrlToCurrentUrlTree (./vendor.bundle.js)
> at Router.prototype.resetStateAndUrl (./vendor.bundle.js)
> at Anonymous function (./vendor.bundle.js)
> at ZoneDelegate.prototype.invoke (./polyfills.bundle.js)
> at onInvoke (./vendor.bundle.js)
> at ZoneDelegate.prototype.invoke (./polyfills.bundle.js)
> at ZoneDelegate.prototype.run (./polyfills.bundle.js)

The environment is Angular 5.2, CLI 1.6.5.

@Tohnmeister, @prasadmamidi7, @rihabesx  did you see the problem when the browser didn't show the navigation buttons in the toolbar?
