### ISSUE TITLE
patchTimer causes errors in jszip

### ISSUE THREAD

**Issue by sstone1** [angular/zone.js#560]
I am using Angular 2 + webpack + [jszip](https://github.com/Stuk/jszip).
jszip has a dependency on `core-js` and `es6-promise` which may be relevant.
When I attempt to use jszip in this configuration, I see this error:

```
EXCEPTION: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'handle.ref')
http://localhost:3000/polyfills.bundle.js:39437:61
setImmediate
http://localhost:3000/main.bundle.js:20622:20
delay@http://localhost:3000/main.bundle.js:461:17
resume@http://localhost:3000/main.bundle.js:21731:20
http://localhost:3000/main.bundle.js:21653:16
ZoneAwarePromise@http://localhost:3000/polyfills.bundle.js:38958:37
accumulate@http://localhost:3000/main.bundle.js:21628:32
```

The error is thrown from this code:

```typescript
// Node.js must additionally support the ref and unref functions.
var handle = (<TimerOptions>task.data).handleId;
if ((<any>handle).ref && (<any>handle).unref) {
  (<any>task).ref = (<any>handle).ref.bind(handle);
  (<any>task).unref = (<any>handle).unref.bind(handle);
}
```
```javascript
// Node.js must additionally support the ref and unref functions.
var handle = task.data.handleId;
if (handle.ref && handle.unref) {
  task.ref = handle.ref.bind(handle);
  task.unref = handle.unref.bind(handle);
}
return task;
```

Changing the code to `if (handle && handle.ref && handle.unref) {` fixes the problem with no obvious side effects.

**Comment by JiaLiPassion** [comment]
could you provide a repo or plunker to reproduce this issue?

**Comment by sstone1** [comment]
Am working on a cut down recreate repo.

**Comment by sstone1** [comment]
https://github.com/sstone1/zone.js-issue-560

`npm install && npm start`
Open up the web page in a browser: [http://localhost:3000](http://localhost:3000)
Observe the following error:

```EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'ref' of undefined
TypeError: Cannot read property 'ref' of undefined
    at http://localhost:3000/polyfills.bundle.js:39285:27
    at setImmediate (eval at createNamedFn (http://localhost:3000/polyfills.bundle.js:39215:17), <anonymous>:3:39)
    at http://localhost:3000/main.bundle.js:2392:15
    at Object.exports.delay (http://localhost:3000/main.bundle.js:399:5)
    at StreamHelper.resume (http://localhost:3000/main.bundle.js:3306:15)
    at http://localhost:3000/main.bundle.js:3228:10
    at new ZoneAwarePromise (http://localhost:3000/polyfills.bundle.js:38806:29)
    at accumulate (http://localhost:3000/main.bundle.js:3203:12)
    at StreamHelper.accumulate (http://localhost:3000/main.bundle.js:3279:16)
    at JSZip.generateAsync (http://localhost:3000/main.bundle.js:7366:53)
    at AppComponent.ngOnInit (http://localhost:3000/main.bundle.js:5075:20)
    at Wrapper_AppComponent.ngDoCheck (/AppModule/AppComponent/wrapper.ngfactory.js:22:53)
```

Problem is triggered by the code here:
https://github.com/sstone1/zone.js-issue-560/blob/master/src/app/app.component.ts#L76

**Comment by JiaLiPassion** [comment]
thank you for the demo, I think the problem is not zone.js, but the browserfy library 
```javascript
  if (canUsePostMessage()) {
	        gScope.setImmediate = function (fn) {
	            timeouts.push(fn);
	            gScope.postMessage(messageName, "*");
	        };
```

this library also monkey-patched setImmediate, but not return a timerId, I think it break the API that setImmediate should return a timerID handle for clearImmediate.

**Comment by sstone1** [comment]
@JiaLiPassion many thanks for diagnosing this and raising the issue against BrowserFS, I'll close this issue now as it doesn't belong with you guys. Everything is working fine with an alternative setImmediate implementation now.
