### ISSUE TITLE
Zone 0.7.x breaks compatibility with Raven-js

### ISSUE THREAD

**Issue by Saegrov** [angular/zone.js#593]
I upgraded to our Angular app to 2.4.1 and Zone.js to 0.7.4 (from 0.6.x) and it seems to have broken compatibility with Raven-js.

I've been digging a bit and it seems that this commit 20b5a5dc1cdd119e2b6ef62eedb271f6daec0e56 introduced the error I'm experiencing. 

The magic of Zone.js and Raven-js is a bit over my knowledge level and I'm unsure if this is considered a bug in either Zone.js or Raven-js.

I've created a plnkr her: [https://plnkr.co/edit/C1706h9xyfNHivsxtH6l?p=preview](https://plnkr.co/edit/C1706h9xyfNHivsxtH6l?p=preview ) that shows the error.

Stacktrace:
```
this.removeAttribute is not a function
    at XMLHttpRequest.desc.get [as onreadystatechange] (https://unpkg.com/zone.js@0.7.4/dist/zone.js:916:26)
    at XMLHttpRequest.send (https://cdn.ravenjs.com/3.7.0/raven.min.js:2:10320)
    at Observable.eval [as _subscribe] (https://unpkg.com/@angular/http@2.4.1/bundles/http.umd.js:1217:22)
    at Observable.subscribe (https://unpkg.com/rxjs/Observable.js:45:27)
    at App.ngOnInit (https://run.plnkr.co/Yk33wUvMk7m5zD4o/src/app.ts!transpiled:33:26)
    at Wrapper_App.ngDoCheck (/AppModule/App/wrapper.ngfactory.js:22:53)
    at CompiledTemplate.proxyViewClass.View_App_Host0.detectChangesInternal (/AppModule/App/host.ngfactory.js:28:17)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12592:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12739:48)
    at ViewRef_.detectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:9819:24)
    at eval (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:8721:71)
    at Array.forEach (native)
    at ApplicationRef_.tick (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:8721:29)
    at ApplicationRef_._loadComponent (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:8696:18)
    at ApplicationRef_.bootstrap (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:8684:18)
    at eval (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:8506:93)
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:8506:46)
    at eval (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:8458:31)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.4/dist/zone.js:242:26)
    at Object.onInvoke (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:4410:41)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.4/dist/zone.js:241:32)
    at Zone.run (https://unpkg.com/zone.js@0.7.4/dist/zone.js:113:43)
    at https://unpkg.com/zone.js@0.7.4/dist/zone.js:520:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.4/dist/zone.js:275:35)
    at Object.onInvokeTask (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:4401:41)
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.4/dist/zone.js:274:40)
    at Zone.runTask (https://unpkg.com/zone.js@0.7.4/dist/zone.js:151:47)
    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.4/dist/zone.js:418:35)
    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.7.4/dist/zone.js:349:25)

```

**Comment by JiaLiPassion** [comment]
Thank you for reporting the issue, I'll look into it.
