### ISSUE TITLE
ElementRef in constructor is undefined after upgrading to 0.7.5

### ISSUE THREAD

**Issue by nickwph** [angular/zone.js#602]
After upgrading to `zone.js 0.7.5`, `ElementRef` of a component is no longer being injected.

```javascript
constructor(private elementRef: ElementRef) {
    // elementRef is undefined
}
```

```
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'nativeElement' of undefined
TypeError: Cannot read property 'nativeElement' of undefined
```

```
Unhandled Promise rejection: Cannot read property 'nativeElement' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'nativeElement' of undefined
    at RadioComponent.CheckboxComponent (http://localhost:3000/main.bundle.js:15686:42)
    at new RadioComponent (http://localhost:3000/main.bundle.js:19857:43)
    at new Wrapper_RadioComponent (/RadioModule/RadioComponent/wrapper.ngfactory.js:6:18)
    at CompiledTemplate.proxyViewClass.View_RadioDemoComponent0.createInternal (/RadioDemoModule/RadioDemoComponent/component.ngfactory.js:177:31)
    at CompiledTemplate.proxyViewClass.AppView.create (http://localhost:3000/vendor.bundle.js:12403:26)
    at CompiledTemplate.proxyViewClass.View_RadioDemoComponent_Host0.createInternal (/RadioDemoModule/RadioDemoComponent/host.ngfactory.js:15:19)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:3000/vendor.bundle.js:12416:26)
    at ComponentFactory.create (http://localhost:3000/vendor.bundle.js:7840:30)
    at ViewContainerRef_.createComponent (http://localhost:3000/vendor.bundle.js:9699:67)
    at RouterOutlet.activate (http://localhost:3000/vendor.bundle.js:29593:43)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:3000/vendor.bundle.js:28903:19)
    at ActivateRoutes.activateRoutes (http://localhost:3000/vendor.bundle.js:28870:29)
    at http://localhost:3000/vendor.bundle.js:28806:61
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:3000/vendor.bundle.js:28806:32) TypeError: Cannot read property 'nativeElement' of undefined
    at RadioComponent.CheckboxComponent (http://localhost:3000/main.bundle.js:15686:42)
    at new RadioComponent (http://localhost:3000/main.bundle.js:19857:43)
    at new Wrapper_RadioComponent (/RadioModule/RadioComponent/wrapper.ngfactory.js:6:18)
    at CompiledTemplate.proxyViewClass.View_RadioDemoComponent0.createInternal (/RadioDemoModule/RadioDemoComponent/component.ngfactory.js:177:31)
    at CompiledTemplate.proxyViewClass.AppView.create (http://localhost:3000/vendor.bundle.js:12403:26)
    at CompiledTemplate.proxyViewClass.View_RadioDemoComponent_Host0.createInternal (/RadioDemoModule/RadioDemoComponent/host.ngfactory.js:15:19)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:3000/vendor.bundle.js:12416:26)
    at ComponentFactory.create (http://localhost:3000/vendor.bundle.js:7840:30)
    at ViewContainerRef_.createComponent (http://localhost:3000/vendor.bundle.js:9699:67)
    at RouterOutlet.activate (http://localhost:3000/vendor.bundle.js:29593:43)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:3000/vendor.bundle.js:28903:19)
    at ActivateRoutes.activateRoutes (http://localhost:3000/vendor.bundle.js:28870:29)
    at http://localhost:3000/vendor.bundle.js:28806:61
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:3000/vendor.bundle.js:28806:32)
```

**Comment by JiaLiPassion** [comment]
@nickwph, can you provide a reproduce repo or plunker?

**Comment by nickwph** [comment]
https://plnkr.co/edit/VjcSCz
There is a `ZoneAwareError`.

```
Unhandled Promise rejection: Cannot set property 'stack' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'stack' of undefined
    at SyntaxError.set [as stack] (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1628:63)
    at assignAll (https://unpkg.com/zone.js@0.7.5/dist/zone.js:704:29)
    at SyntaxError.ZoneAwareError (https://unpkg.com/zone.js@0.7.5/dist/zone.js:775:16)
    at SyntaxError.BaseError [as constructor] (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1590:18)
    at new SyntaxError (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1793:18)
    at TemplateParser.parse (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:11210:21)
    at JitCompiler._compileTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27480:70)
    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27363:64)
    at Set.forEach (native)
    at JitCompiler._compileComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27363:21)
    at createResult (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27246:21)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.5/dist/zone.js:242:26)
    at Zone.run (https://unpkg.com/zone.js@0.7.5/dist/zone.js:113:43)
    at https://unpkg.com/zone.js@0.7.5/dist/zone.js:535:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.5/dist/zone.js:275:35) TypeError: Cannot set property 'stack' of undefined
    at SyntaxError.set [as stack] (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1628:63)
    at assignAll (https://unpkg.com/zone.js@0.7.5/dist/zone.js:704:29)
    at SyntaxError.ZoneAwareError (https://unpkg.com/zone.js@0.7.5/dist/zone.js:775:16)
    at SyntaxError.BaseError [as constructor] (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1590:18)
    at new SyntaxError (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1793:18)
    at TemplateParser.parse (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:11210:21)
    at JitCompiler._compileTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27480:70)
    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27363:64)
    at Set.forEach (native)
    at JitCompiler._compileComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27363:21)
    at createResult (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27246:21)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.5/dist/zone.js:242:26)
    at Zone.run (https://unpkg.com/zone.js@0.7.5/dist/zone.js:113:43)
    at https://unpkg.com/zone.js@0.7.5/dist/zone.js:535:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.5/dist/zone.js:275:35)
```

**Comment by JiaLiPassion** [comment]
@nickwph , Thank you for the plunker, I have made a new PR #597 to fix this issue.

**Comment by nickwph** [comment]
Awesome! 😄

**Comment by JiaLiPassion** [comment]
0.7.6 has been released, please try it.

**Comment by ivaris** [comment]
Unhandled Promise rejection: Cannot set property 'stack' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'stack' of undefined.

This happens when i use below to display array of strings.

<li *ngFor="#course of courses">
	{{ course }}
	</li>

**Comment by JiaLiPassion** [comment]
@ivaris Could you provide a reproduce repo or plunker?

**Comment by ivaris** [comment]
https://github.com/ivaris/uiprojects/tree/development/myAngular2

**Comment by JiaLiPassion** [comment]
@ivaris , your repo don't have any src, and can't be download, could you check it again? Or maybe you can just zip your working copy (without node_modules) and paste here by dragging the file.

**Comment by JiaLiPassion** [comment]
close for not be able to reproduce.
