### ISSUE TITLE
Error in the browser after updating to the latest version/

### ISSUE THREAD

**Issue by anrepppp** [angular/zone.js#619]
Sorry, for the long dump. After updating the zone.js and all the plugins to the latest version i am seeing the below error in my browser.Can, you please help me to understand about the error. 
Here is the error:

zone.js:420Unhandled Promise rejection: appInits[i] is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: appInits[i] is not a function(…) TypeError: appInits[i] is not a function
    at new ApplicationInitStatus (http://localhost:4200/vendor.bundle.js:61423:45)
    at NgModuleInjector.AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:610:36)
    at NgModuleInjector.create (http://localhost:4200/vendor.bundle.js:85681:76)
    at NgModuleFactory.create (http://localhost:4200/vendor.bundle.js:85649:18)
    at http://localhost:4200/vendor.bundle.js:61858:61
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:168264:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:48742:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:168263:32)
    at Zone.run (http://localhost:4200/vendor.bundle.js:168135:43)
    at NgZone.run (http://localhost:4200/vendor.bundle.js:48611:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:4200/vendor.bundle.js:61856:23)
    at http://localhost:4200/vendor.bundle.js:61907:59
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:168264:26)
    at Zone.run (http://localhost:4200/vendor.bundle.js:168135:43)
    at http://localhost:4200/vendor.bundle.js:168557:57consoleError @ zone.js:420_loop_1 @ zone.js:449drainMicroTaskQueue @ zone.js:453Promise.resolve (async)scheduleQueueDrain @ zone.js:406scheduleMicroTask @ zone.js:414ZoneDelegate.scheduleTask @ zone.js:258Zone.scheduleMicroTask @ zone.js:165scheduleResolveOrReject @ zone.js:533ZoneAwarePromise.then @ zone.js:622ZoneAwarePromise.all @ zone.js:602JitCompiler._loadModules @ compiler.js:173JitCompiler._compileModuleAndComponents @ compiler.js:125JitCompiler.compileModuleAsync @ compiler.js:91PlatformRef_._bootstrapModuleWithZone @ application_ref.js:401PlatformRef_.bootstrapModule @ application_ref.js:376732 @ main.ts:12__webpack_require__ @ bootstrap 5683e8e…:521530 @ .*$:7__webpack_require__ @ bootstrap 5683e8e…:52webpackJsonpCallback @ bootstrap 5683e8e…:23(anonymous function) @ main.bundle.js:1
zone.js:422ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): TypeError: appInits[i] is not a function
TypeError: appInits[i] is not…, rejection: TypeError: appInits[i] is not a function
    at new ApplicationInitStatus (http://localhost:4200/ven…, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask}

**Comment by JiaLiPassion** [comment]
@anvesh48, I think it is your application error, could you post your repo somewhere or make a plunker?

**Comment by anvesh48** [comment]
Here is my package.json file, i didn't changed my code from long-time. I have no idea what changes are in the plugin that is causing the isssue.

{

  "angular-cli": {},
  "scripts": {
    "start": "tslint \"src/**/*.ts\" --force && ng serve --proxy-config proxy.conf.json",
    "build": "tslint \"src/**/*.ts\" && ng test --watch=false && ng build",
    "lint": "tslint \"src/**/*.ts\" --force",
    "postinstall": "typings install",
    "test": "ng test --watch=false",
    "test:watch": "ng test --watch=true",
    "typings": "typings",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.13",
    "@ng-idle/core": "2.0.0-beta.4",
    "@ng-idle/keepalive": "2.0.0-beta.4",
    "bootstrap": "4.0.0-alpha.4",
    "components-font-awesome": "^4.7.0",
    "core-js": "2.4.1",
    "jquery": "^3.1.0",
    "rxjs": "5.0.3",
    "ts-helpers": "^1.1.1",
    "tslint": "3.13.0",
    "typescript": "2.0.3",
    "typings": "^1.5.0",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/lodash": "^4.14.37",
    "angular-cli": "1.0.0-beta.21",
    "codelyzer": "~0.0.26",
    "graceful-fs": "4.1.11",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.4.0",
    "less": "^2.7.1",
    "lodash": "^4.17.4",
    "minimatch": "3.0.3",
    "moment": "^2.15.1",
    "protractor": "5.0.0",
    "ts-node": "1.2.1",
    "ag-grid": "7.2.2",
    "ag-grid-ng2": "7.2.2",
    "angular2-hotkeys": "^0.5.0",
    "angular2-toaster": "^1.0.2",
    "ng-click-outside": "2.0.2",
    "ng2-material-dropdown": "^0.6.4",
    "ng2-tag-input": "^0.7.4"
  }
}

**Comment by JiaLiPassion** [comment]
Please post a repo or a plunker to reproduce your issue.
