### ISSUE TITLE
long-stack-trace zone breaks SourceMaps on stack traces

### ISSUE THREAD

**Issue by tbosch** [angular/zone.js#661]
Looks like the extra line in the stack trace breaks source maps (e.g. `  -------------   Elapsed: 4137 ms; At: Mon Mar 06 2017 11:00:38 GMT-0800 (PST)   -------------  `).

This does not work (which is used by long-stack-trace zone)
```
var e = new Error();
e.stack = `at ErrorComponent.createError (http://localhost:8000/all/playground/src/sourcemap/index.js:21:64) [angular]
    at Object.eval [as handleEvent] (http://localhost:8000/nggen/ExampleModule/ErrorComponent.ngfactory.js:25:26) [angular]
    at handleEvent (http://localhost:8000/all/@angular/core/src/view/view.js:126:41) [angular]
    at callWithDebugContext (http://localhost:8000/all/@angular/core/src/view/services.js:428:25) [angular]
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8000/all/@angular/core/src/view/services.js:134:12) [angular]
    at Object.dispatchEvent (http://localhost:8000/all/@angular/core/src/view/util.js:85:29) [angular]
    at http://localhost:8000/all/@angular/core/src/view/element.js:184:45 [angular]
    at HTMLButtonElement.<anonymous> (http://localhost:8000/all/@angular/platform-browser/src/dom/dom_renderer.js:60:36) [angular]
    at Object.onInvokeTask (http://localhost:8000/all/@angular/core/src/zone/ng_zone.js:230:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:8000/all/playground/vendor/zone.js:261:40) [angular]
    at Zone.runTask (http://localhost:8000/all/playground/vendor/zone.js:151:47) [<root> => angular]
    at HTMLButtonElement.ZoneTask.invoke (http://localhost:8000/all/playground/vendor/zone.js:332:33) [<root>]
  -------------   Elapsed: 4137 ms; At: Mon Mar 06 2017 11:00:38 GMT-0800 (PST)   -------------  
    at getStacktraceWithUncaughtError (http://localhost:8000/all/playground/vendor/long-stack-trace-zone.js:33:12) [angular]
    at new LongStackTrace (http://localhost:8000/all/playground/vendor/long-stack-trace-zone.js:27:22) [angular]
    at Object.onScheduleTask (http://localhost:8000/all/playground/vendor/long-stack-trace-zone.js:83:18) [angular]
`;
console.error(e);
```

This works:
```
var e = new Error();
e.stack = `at ErrorComponent.createError (http://localhost:8000/all/playground/src/sourcemap/index.js:21:64) [angular]
    at Object.eval [as handleEvent] (http://localhost:8000/nggen/ExampleModule/ErrorComponent.ngfactory.js:25:26) [angular]
    at handleEvent (http://localhost:8000/all/@angular/core/src/view/view.js:126:41) [angular]
    at callWithDebugContext (http://localhost:8000/all/@angular/core/src/view/services.js:428:25) [angular]
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8000/all/@angular/core/src/view/services.js:134:12) [angular]
    at Object.dispatchEvent (http://localhost:8000/all/@angular/core/src/view/util.js:85:29) [angular]
    at http://localhost:8000/all/@angular/core/src/view/element.js:184:45 [angular]
    at HTMLButtonElement.<anonymous> (http://localhost:8000/all/@angular/platform-browser/src/dom/dom_renderer.js:60:36) [angular]
    at Object.onInvokeTask (http://localhost:8000/all/@angular/core/src/zone/ng_zone.js:230:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:8000/all/playground/vendor/zone.js:261:40) [angular]
    at BREAK =============== 500 ms elapse  ===== (http://localhost:8000/path:1:2)
    at HTMLButtonElement.ZoneTask.invoke (http://localhost:8000/all/playground/vendor/zone.js:332:33) [<root>]
    at getStacktraceWithUncaughtError (http://localhost:8000/all/playground/vendor/long-stack-trace-zone.js:33:12) [angular]
(http://localhost:8000/all/playground/vendor/zone.js:332:33) [<root>]
`;
console.error(e);
```

**Comment by JiaLiPassion** [comment]
@tbosch , I would like to look into this issue, based on the https://github.com/angular/angular/issues/15185, the source map will not be correct when SyntaxError, so I just modify the html template with some wrong syntax , so I can reproduce? If you can provide a reproduce repository, it will help, thank you.

**Comment by JiaLiPassion** [comment]
close for not be able to reproduce.
