### ISSUE TITLE
Zone.js tries to mutate immutable Error

### ISSUE THREAD

**Issue by martvaha** [angular/zone.js#663]
I am not sure whether it is a bug or not but after 0.7.5 I get an error with every dispatched action containing an Error as payload. The error occurs in development mode because I am using [ngrx-store-freeze](https://github.com/codewareio/ngrx-store-freeze) to prevent inadvertent state mutations and it seems to make action payloads immutable.

Here is the error message:
```
TypeError: Can't add property __zone_symbol__stack, object is not extensible
    at AccessError.get [as stack] (http://localhost:4200/polyfills.bundle.js:878:36)
    at http://localhost:4200/vendor.bundle.js:165052:9
    at Array.forEach (native)
    at deepFreeze (http://localhost:4200/vendor.bundle.js:165049:33)
    at http://localhost:4200/vendor.bundle.js:173861:13
    at reducer (http://localhost:4200/main.bundle.js:9889:16)
    at computeNextEntry (http://localhost:4200/vendor.bundle.js:164272:21)
    at recomputeStates (http://localhost:4200/vendor.bundle.js:164303:13)
    at http://localhost:4200/vendor.bundle.js:164485:26
    at ScanSubscriber.accumulator (http://localhost:4200/vendor.bundle.js:130270:37)
    at ScanSubscriber._tryNext (http://localhost:4200/vendor.bundle.js:101620:27)
    at ScanSubscriber._next (http://localhost:4200/vendor.bundle.js:101613:25)
    at ScanSubscriber.Subscriber.next (http://localhost:4200/vendor.bundle.js:542:18)
    at WithLatestFromSubscriber._next (http://localhost:4200/vendor.bundle.js:63783:34)
    at WithLatestFromSubscriber.Subscriber.next (http://localhost:4200/vendor.bundle.js:542:18)
```

Everything works fine with 0.7.5 and 0.7.4 but both 0.7.6 and 0.7.7 throw this error.

**Comment by JiaLiPassion** [comment]
@martvaha , can you provide a plunker or repo to reproduce?

**Comment by martvaha** [comment]
Here's a simple plunker: https://plnkr.co/edit/cfPhi4pXtGuwsOk9Yqi4

**Comment by JiaLiPassion** [comment]
@martvaha , there is a walk around https://plnkr.co/edit/W6x3ej4nI663eMhOOozc?p=preview, I would like to consider it more deeply to find out zone.js should fix it or not.

**Comment by martvaha** [comment]
Alright, thanks for the workaround in the meantime.

**Comment by hxuanhung** [comment]
I got the same problem with zone.js 0.8.0 and ngrx-store-freeze.

**Comment by JiaLiPassion** [comment]
zone.js 0.8.4 has resolved this issue, please update to it.

**Comment by martvaha** [comment]
0.8.4 solved the issue, thanks!
