### ISSUE TITLE
local storage access denied exception not catchable

### ISSUE THREAD

**Issue by lvanderbijl** [angular/zone.js#694]
I'm running an angular 2 application that needs to use local storage.

I have a route resolver that, as part of the resolve process tries to retrieve settings from localStorage:
`localStorage.getItem('something')`

This works fine in Chrome, FF, Safari and Edge.
In IE 11 or below i get an access denied error.

'Error: Uncaught (in promise): Error: Access is denied.
Error: Access is denied.
at localStorage.get (https://mysite/vendor.bundle.js:135344:13105)
//some lines omitted for brevity
at _UserResolver_56.get (Function code:191:44)
at AppModuleInjector.prototype.getInternal (Function code:413:41)
at NgModuleInjector.prototype.get (https://mysite/vendor.bundle.js:82719:9)
at PreActivation.prototype.getToken (https://mysite/vendor.bundle.js:39848:9)
at Anonymous function (https://mysite/vendor.bundle.js:39835:'

This occurs because IE11 sets local storage as a privileged api call. I can fix it by add the site to my trusted sites - but that's not a viable solution for regular site users.

The problem is I can't find any way of catching this error.

I've tried wrapping localStorage.get in a try catch - even tried all the recommended ways of detecting localStorage but get the same error. 

I used a FallbackStorage implementation - same problem.

I've tried a catch at the end of the user resolver promise but that doesn't do it either.

Is there something in the way zones.js manages injection/instantiation that means I can't catch access denied errors?

**Comment by lvanderbijl** [comment]
Found the cause... apologies this is not an issue with zone js.
