### ISSUE TITLE
Uncaught NoAnnotationError {_nativeError: ZoneAwareError}

### ISSUE THREAD

**Issue by miliu99** [angular/zone.js#714]
My angular 2 (v 2.0) project using webpack was working until I try to integrate ng2-bootstrap-modal, which requires me to upgrade everything to a newer version. Since then, I trapped in a rabbit hole. Now, I got everything to (almost) the latest, and my npm start doesn't show any error, however, my project doesn't start up. The browse log shows me the follow error:

```
NoAnnotationError
_nativeError
:
Error: Cannot resolve all parameters for 'Parser'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Parser' is decorated with Injectable. at NoAnnotationError.BaseError [as constructor] (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:1244:31) [<root>] at new NoAnnotationError (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:1568:20) [<root>] at _dependenciesFor (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2410:19) [<root>] at resolveReflectiveFactory (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2289:28) [<root>] at resolveReflectiveProvider (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2314:86) [<root>] at Array.map (native) [<root>] at resolveReflectiveProviders (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2323:52) [<root>] at Function.ReflectiveInjector.resolve (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2542:20) [<root>] at Function.ReflectiveInjector.resolveAndCreate (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2575:83) [<root>] at JitCompilerFactory.createCompiler (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:113:2), <anonymous>:27952:78) [<root>] at PlatformRef_._bootstrapModuleWithZone (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:8071:61) [<root>] at PlatformRef_.bootstrapModule (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:8058:25) [<root>] at eval (eval at <anonymous> (http://localhost:3000/bundle/main.js:5:2), <anonymous>:4:53) [<root>] at Object.<anonymous> (http://localhost:3000/bundle/main.js:5:2) [<root>]
message
:
"Cannot resolve all parameters for 'Parser'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Parser' is decorated with Injectable."
originalStack
:
"Error: Cannot resolve all parameters for 'Parser'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Parser' is decorated with Injectable.↵    at ZoneAwareError (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:2319:2), <anonymous>:917:33)↵    at NoAnnotationError.BaseError [as constructor] (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:1244:31)↵    at new NoAnnotationError (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:1568:20)↵    at _dependenciesFor (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2410:19)↵    at resolveReflectiveFactory (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2289:28)↵    at resolveReflectiveProvider (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2314:86)↵    at Array.map (native)↵    at resolveReflectiveProviders (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2323:52)↵    at Function.ReflectiveInjector.resolve (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2542:20)↵    at Function.ReflectiveInjector.resolveAndCreate (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2575:83)↵    at JitCompilerFactory.createCompiler (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:113:2), <anonymous>:27952:78)↵    at PlatformRef_._bootstrapModuleWithZone (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:8071:61)↵    at PlatformRef_.bootstrapModule (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:8058:25)↵    at eval (eval at <anonymous> (http://localhost:3000/bundle/main.js:5:2), <anonymous>:4:53)↵    at Object.<anonymous> (http://localhost:3000/bundle/main.js:5:2)"
stack
:
"Error: Cannot resolve all parameters for 'Parser'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Parser' is decorated with Injectable.↵    at NoAnnotationError.BaseError [as constructor] (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:1244:31) [<root>]↵    at new NoAnnotationError (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:1568:20) [<root>]↵    at _dependenciesFor (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2410:19) [<root>]↵    at resolveReflectiveFactory (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2289:28) [<root>]↵    at resolveReflectiveProvider (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2314:86) [<root>]↵    at Array.map (native) [<root>]↵    at resolveReflectiveProviders (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2323:52) [<root>]↵    at Function.ReflectiveInjector.resolve (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2542:20) [<root>]↵    at Function.ReflectiveInjector.resolveAndCreate (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2575:83) [<root>]↵    at JitCompilerFactory.createCompiler (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:113:2), <anonymous>:27952:78) [<root>]↵    at PlatformRef_._bootstrapModuleWithZone (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:8071:61) [<root>]↵    at PlatformRef_.bootstrapModule (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:8058:25) [<root>]↵    at eval (eval at <anonymous> (http://localhost:3000/bundle/main.js:5:2), <anonymous>:4:53) [<root>]↵    at Object.<anonymous> (http://localhost:3000/bundle/main.js:5:2) [<root>]"
zoneAwareStack
:
"Error: Cannot resolve all parameters for 'Parser'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Parser' is decorated with Injectable.↵    at NoAnnotationError.BaseError [as constructor] (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:1244:31) [<root>]↵    at new NoAnnotationError (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:1568:20) [<root>]↵    at _dependenciesFor (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2410:19) [<root>]↵    at resolveReflectiveFactory (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2289:28) [<root>]↵    at resolveReflectiveProvider (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2314:86) [<root>]↵    at Array.map (native) [<root>]↵    at resolveReflectiveProviders (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2323:52) [<root>]↵    at Function.ReflectiveInjector.resolve (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2542:20) [<root>]↵    at Function.ReflectiveInjector.resolveAndCreate (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:2575:83) [<root>]↵    at JitCompilerFactory.createCompiler (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:113:2), <anonymous>:27952:78) [<root>]↵    at PlatformRef_._bootstrapModuleWithZone (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:8071:61) [<root>]↵    at PlatformRef_.bootstrapModule (eval at <anonymous> (http://localhost:3000/bundle/vendor.js:119:2), <anonymous>:8058:25) [<root>]↵    at eval (eval at <anonymous> (http://localhost:3000/bundle/main.js:5:2), <anonymous>:4:53) [<root>]↵    at Object.<anonymous> (http://localhost:3000/bundle/main.js:5:2) [<root>]"
__proto__
:
Object
```

It sounds like some of the components are missing Injectable, but which one? How do I find it out? Migrating to Angular2 is becoming a nightmare.

**Comment by JiaLiPassion** [comment]
@miliu99 , I think this is not zone.js issue, please post it in stackoverflow.

**Comment by sleepydada** [comment]
@miliu99 did you solve it?
