### ISSUE TITLE
Stack trace with zone and third party libraries

### ISSUE THREAD

**Issue by irossimoline** [angular/zone.js#821]
I am building a custom error handler in an Angular.io project to log my application errors, and the stack trace associated with them.
I enabled long stack traces in zone.js to get the specific context where the error happened, specifically because if we are working with promises/observables, we must know the origin of them.
I managed to enable long stack traces, and filter zone's specific stack trace (importing zone-error.js in my project, and leaving it's default behavior).
The problem is that when i throw an error in a Promise, y get a **huge** full stack, but only few lines are of my interest. In this case, the main stack trace is from rxjs, which is not part of my application code, but it's a library that angular.io uses to handle promises/observables. How can i filter the information I need? Is any correct way or workaround to have a cleaner stack trace?
I read the API documentation, but none configuration seemed to help me.

`ERROR Error: Uncaught (in promise): Response with status: 0  for URL: null
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3648:31) [angular]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3619:17) [angular]
    at http://localhost:4200/polyfills.bundle.js:3696:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:48105:37) [angular]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3462:35) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:3368:25) [<root>]
    at ____________________Elapsed_3_ms__At__Sat_Jun_17_2017_21_28_26_GMT_0300__Montevideo_Standard_Time_ (http://localhost)
    at getStacktraceWithUncaughtError (http://localhost:4200/polyfills.bundle.js:2454:12) [angular]
    at new LongStackTrace (http://localhost:4200/polyfills.bundle.js:2448:22) [angular]
    at Object.onScheduleTask (http://localhost:4200/polyfills.bundle.js:2524:22) [angular]
    at Object.onScheduleTask (http://localhost:4200/polyfills.bundle.js:3178:29) [angular]
    at scheduleResolveOrReject (http://localhost:4200/polyfills.bundle.js:3694:14) [angular]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3643:21) [angular]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3619:17) [angular]
    at http://localhost:4200/polyfills.bundle.js:3696:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:48105:37) [angular]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3462:35) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:3368:25) [<root>]
    at ____________________Elapsed_2_ms__At__Sat_Jun_17_2017_21_28_26_GMT_0300__Montevideo_Standard_Time_ (http://localhost)
    at getStacktraceWithUncaughtError (http://localhost:4200/polyfills.bundle.js:2454:12) [angular]
    at new LongStackTrace (http://localhost:4200/polyfills.bundle.js:2448:22) [angular]
    at Object.onScheduleTask (http://localhost:4200/polyfills.bundle.js:2524:22) [angular]
    at Object.onScheduleTask (http://localhost:4200/polyfills.bundle.js:3178:29) [angular]
    at scheduleResolveOrReject (http://localhost:4200/polyfills.bundle.js:3694:14) [angular]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3643:21) [angular]
    at http://localhost:4200/polyfills.bundle.js:3574:17 [angular]
    at SafeSubscriber._error (http://localhost:4200/vendor.bundle.js:5924:85) [angular]
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:4414:16) [angular]
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.error (http://localhost:4200/vendor.bundle.js:4373:26) [angular]
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._error (http://localhost:4200/vendor.bundle.js:4304:26) [angular]
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.error (http://localhost:4200/vendor.bundle.js:4278:18) [angular]
    at XMLHttpRequest.onError (http://localhost:4200/vendor.bundle.js:66498:34) [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:48105:37) [angular]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:3364:38) [<root>]
    at ____________________Elapsed_2006_ms__At__Sat_Jun_17_2017_21_28_24_GMT_0300__Montevideo_Standard_Time_ (http://localhost)
    at getStacktraceWithUncaughtError (http://localhost:4200/polyfills.bundle.js:2454:12) [angular]
    at new LongStackTrace (http://localhost:4200/polyfills.bundle.js:2448:22) [angular]
    at Object.onScheduleTask (http://localhost:4200/polyfills.bundle.js:2524:22) [angular]
    at Object.onScheduleTask (http://localhost:4200/polyfills.bundle.js:3178:29) [angular]
    at zoneAwareAddListener (http://localhost:4200/polyfills.bundle.js:4157:14) [angular]
    at XMLHttpRequest.proto.(anonymous function) [as addEventListener] (http://localhost:4200/polyfills.bundle.js:4304:20) [angular]
    at Observable._subscribe (http://localhost:4200/vendor.bundle.js:66528:18) [angular]
    at Observable.webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe (http://localhost:4200/vendor.bundle.js:3810:25) [angular]
    at Observable.webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe (http://localhost:4200/vendor.bundle.js:3798:65) [angular]
    at http://localhost:4200/vendor.bundle.js:5924:15 [angular]
    at new ZoneAwarePromise (http://localhost:4200/polyfills.bundle.js:3712:29) [angular]
    at Observable.toPromise (http://localhost:4200/vendor.bundle.js:5922:12) [angular]
    at LoginService.webpackJsonp.../../../../../src/app/login.service.ts.LoginService.login (http://localhost:4200/main.bundle.js:158:14) [angular]
    at AppComponent.webpackJsonp.../../../../../src/app/app.component.ts.AppComponent.ngOnInit (http://localhost:4200/main.bundle.js:64:27) [angular]
    at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:55104:19) [angular]
    at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:56592:17) [angular]
    at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:56531:16) [angular]
    at debugCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:57390:59) [angular]
    at debugCheckDirectivesFn (http://localhost:4200/vendor.bundle.js:57331:13) [angular]
    at Object.eval [as updateDirectives] (ng:///AppModule/AppComponent_Host.ngfactory.js:9:5) [angular]
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:4200/vendor.bundle.js:57316:21) [angular]
    at checkAndUpdateView (http://localhost:4200/vendor.bundle.js:56498:14) [angular]
    at callWithDebugContext (http://localhost:4200/vendor.bundle.js:57716:42) [angular]
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:4200/vendor.bundle.js:57256:12) [angular]
    at ViewRef_.webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:54437:18) [angular]
    at http://localhost:4200/vendor.bundle.js:49046:63 [angular]
    at Array.forEach (<anonymous>) [angular]
    at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick (http://localhost:4200/vendor.bundle.js:49046:25) [angular]
    at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_._loadComponent (http://localhost:4200/vendor.bundle.js:49022:14) [angular]
    at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:49010:14) [angular]
    at http://localhost:4200/vendor.bundle.js:48786:81 [angular]
    at Array.forEach (<anonymous>) [angular]
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:48786:44) [angular]
    at http://localhost:4200/vendor.bundle.js:48748:27 [angular]
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:48114:37) [angular]
    at http://localhost:4200/polyfills.bundle.js:3696:57 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:48105:37) [angular]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3462:35) [<root>]
    at <anonymous> [<root>]
    at ____________________Elapsed_36_ms__At__Sat_Jun_17_2017_21_28_24_GMT_0300__Montevideo_Standard_Time_ (http://localhost)
    at getStacktraceWithUncaughtError (http://localhost:4200/polyfills.bundle.js:2454:12) [angular]
    at new LongStackTrace (http://localhost:4200/polyfills.bundle.js:2448:22) [angular]
    at Object.onScheduleTask (http://localhost:4200/polyfills.bundle.js:2524:22) [angular]
    at Object.onScheduleTask (http://localhost:4200/polyfills.bundle.js:3178:29) [angular]
    at scheduleResolveOrReject (http://localhost:4200/polyfills.bundle.js:3694:14) [angular]
    at ZoneAwarePromise.then (http://localhost:4200/polyfills.bundle.js:3783:17) [angular]
    at http://localhost:4200/vendor.bundle.js:48747:47 [angular]
    at _callAndReportToErrorHandler (http://localhost:4200/vendor.bundle.js:48646:39) [angular]
    at http://localhost:4200/vendor.bundle.js:48744:20 [angular]
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:48114:37) [angular]
    at NgZone.webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run (http://localhost:4200/vendor.bundle.js:47982:62) [<root>]
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:4200/vendor.bundle.js:48735:23) [<root>]
    at http://localhost:4200/vendor.bundle.js:48777:59 [<root>]
    at http://localhost:4200/polyfills.bundle.js:3696:57 [<root>]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3462:35) [<root>]
    at <anonymous> [<root>]`

**Comment by JiaLiPassion** [comment]
@irossimoline, you can add 

```
import 'zone.js/dist/zone-error'; 
```

in `polyfills.ts` or just load this file yourself in your application, then it will basically only output the `non zone` stack trace.

**Comment by irossimoline** [comment]
I'm already importing zone-error in polyfills.ts:

`import 'zone.js/dist/zone-error.js';
  import 'zone.js/dist/long-stack-trace-zone.js';`

Also I've already updated the packages that were out of date.
Stack trace keep being the same.
Another thing I can try?

**Comment by JiaLiPassion** [comment]
@irossimoline , `zone-error` only trim the `zone.js` related stack trace, for `rxjs` or other libraries, you have to do it yourself.

- You may travel the `stackFrames` and check the `filename`, this will only work in development mode.

-  or do some `pre detection` just like `zonejs` did. 

```
someDetectionObservable.subscribe(() => {
   blackListFrames = new Error().stack;
});
```

**Comment by irossimoline** [comment]
@JiaLiPassion, thank you for your answer. 

I would like to build a solution that works independently of the environment, so i'll pick the second option, but I don't realize the way I can get that working. Could you please shed some light? I'm not seeing where I should place this logic to get this done.

**Comment by JiaLiPassion** [comment]
@irossimoline , you can check https://github.com/angular/zone.js/blob/master/lib/common/error-rewrite.ts#L269, the idea is just create a `error` in the `function` you want to ignore it's stack trace, and store it into a `blackListStackFrames` array.

**Comment by JiaLiPassion** [comment]
Close for now.
