### ISSUE TITLE
"Error: 1 timer(s) still in the queue" starting on zone@0.8.14

### ISSUE THREAD

**Issue by emilio-martinez** [angular/zone.js#845]
I'm experiencing a regression issue when upgrading from zone@0.8.12 to zone@0.8.14 while using the Angular 4.3.0 unit test utilities. I now get `Error: 1 timer(s) still in the queue.`—more details below.

I'm filling the issue on this repo since I believe it's related to Zone's Scheduler. Just to double check, I've tested making the zone upgrade the only change in before/after, so I can assure there's no other dependency change that may cause this in my situation.

Of course, I'm not really utilizing Zone directly, but in essence, the situation where this is occurring for me is as follows:

```ts
it('should work', fakeAsync(() => {
  // --------------------------------------------- //
  // code invoking a Dialog component to open here //
  // --------------------------------------------- //

  viewContainerFixture.detectChanges();
  flushMicrotasks(); // Uh oh. The test throws here!

  // Never reaches expectation
  expect(expression).toBe('...');
}));
```

However, calling `tick` before `flushMicrotasks` clears the error, not that it's really a fix since it didn't seem to be an issue before. Below my stack trace in case it's useful.

```
Error: 1 timer(s) still in the queue.
  at Object.<anonymous> (webpack:///node_modules/@angular/core/@angular/core/testing.js:350:22 <- src/test.ts:11703:914)
  at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:391:25 <- src/test.ts:24777:1154)
  at ProxyZoneSpec.onInvoke (webpack:///node_modules/zone.js/dist/proxy.js:79:38 <- src/test.ts:25211:2160)
  at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:390:31 <- src/test.ts:24777:1050)
  at Zone.run (webpack:///node_modules/zone.js/dist/zone.js:141:42 <- src/test.ts:24761:2925)
  at Object.<anonymous> (webpack:///node_modules/zone.js/dist/jasmine-patch.js:104:33 <- src/test.ts:25260:131)
  at webpack:///node_modules/@angular/core/@angular/core/testing.js:91:16 <- src/test.ts:11633:46
  at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:391:25 <- src/test.ts:24777:1154)
  at AsyncTestZoneSpec.onInvoke (webpack:///node_modules/zone.js/dist/async-test.js:49:38 <- src/test.ts:25115:156)
  at ProxyZoneSpec.onInvoke (webpack:///node_modules/zone.js/dist/proxy.js:76:38 <- src/test.ts:25211:2040)
  at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:390:31 <- src/test.ts:24777:1050)
  at Zone.run (webpack:///node_modules/zone.js/dist/zone.js:141:42 <- src/test.ts:24761:2925)
  at AsyncTestZoneSpec._finishCallback (webpack:///node_modules/@angular/core/@angular/core/testing.js:86:24 <- src/test.ts:11632:13)
  at webpack:///node_modules/zone.js/dist/async-test.js:38:30 <- src/test.ts:25112:139
  at ZoneDelegate.invokeTask (webpack:///node_modules/zone.js/dist/zone.js:424:30 <- src/test.ts:24777:2120)
  at Zone.runTask (webpack:///node_modules/zone.js/dist/zone.js:191:46 <- src/test.ts:24766:417)
  at ZoneTask.invokeTask (webpack:///node_modules/zone.js/dist/zone.js:498:33 <- src/test.ts:24779:1209)
  at ZoneTask.invoke (webpack:///node_modules/zone.js/dist/zone.js:487:47 <- src/test.ts:24779:1036)
  at timer (webpack:///node_modules/zone.js/dist/zone.js:1823:28 <- src/test.ts:24944:248)
```

**Comment by JiaLiPassion** [comment]
Thank you for posting the issue, I will check it.

**Comment by emilio-martinez** [comment]
@JiaLiPassion Sure thing! 

Here you go: https://github.com/emilio-martinez/issue-repro-zone845
Issue repro details in the README. Basically you just install and `ng test`

**Comment by JiaLiPassion** [comment]
@emilio-martinez , thank you, I can reproduce now.

**Comment by vikerman** [comment]
Hi - @JiaLiPassion diagnosis is correct. I actually have a pending commit for Zone so that we don't end up breaking existing tests that use RequestAnimationFrame by not throwing the error for pending RAF-s. Will get it into next release of Zone.js

**Comment by JiaLiPassion** [comment]
@vikerman , got it, thank you !

**Comment by emilio-martinez** [comment]
I'm not seeing the issue on my end anymore. Fixed as of https://github.com/angular/zone.js/commit/eca04b0?

**Comment by vikerman** [comment]
Yes. Fixed. Thanks for verifying!

**Comment by EvanSevy** [comment]
I'm getting this error after updating all my package.json packages.  Specifically for zone.js I'm at "^0.9.1".  So is the correct way to fix this is to just put a tick() at the end of my 'it' test?  

I'm not quite following what the problem is.  What is a requestAnimationFrame?  I see that it somehow hooks into the browser rendering cycle and looks to handle refreshing of some sort, but how does it relate to testing?  And why am I have this problem now and not before?
