### ISSUE TITLE
IE10 - Access Denied

### ISSUE THREAD

**Issue by angular2fan** [angular/zone.js#926]
Hi, I am using Material2 Beta 12 version's MATDialogModule. I am running into an issue when I open the Dialog in IE10. Its failing with the error below.

"TypeError: Accessing the 'arguments' property of a function is not allowed in strict mode\n  
at Zone.prototype.runTask (..................../polyfills.bundle.js:10644:17)\n   
at ZoneTask.invokeTask (......./polyfills.bundle.js:10950:17)\n   
at invoke (......./polyfills.bundle.js:10939:21)\n   
at timer (........./polyfills.bundle.js:12185:17)"

Steps to reproduce:
Open the Material2 Dialog in IE10 and in the console there should be an "Access Denied" error .

**Comment by JiaLiPassion** [comment]
@angular2fan , could you provide a reproduce repo?

**Comment by JiaLiPassion** [comment]
Close it because can not reproduce.
