### ISSUE TITLE
Unknown macroTask scheduled in fake async test: HTMLCanvasElement.toBlob

### ISSUE THREAD

**Issue by eric-simonton-sama** [angular/zone.js#937]
I get the following error testing code that uses `canvas.toBlob` within a fakeAsync test:
```
Uncaught Error: Unknown macroTask scheduled in fake async test: HTMLCanvasElement.toBlob
    at FakeAsyncTestZoneSpec.webpackJsonp.601.FakeAsyncTestZoneSpec.onScheduleTask (http://localhost:3000/packs/tests.js:5338:35)
    at ProxyZoneSpec.webpackJsonp.600.ProxyZoneSpec.onScheduleTask (http://localhost:3000/packs/tests.js:4957:39)
    at ZoneDelegate.598.ZoneDelegate.scheduleTask (http://localhost:3000/packs/polyfills.js:2706:51)
    at Zone.598.Zone.scheduleTask (http://localhost:3000/packs/polyfills.js:2537:43)
    at Zone.598.Zone.scheduleMacroTask (http://localhost:3000/packs/polyfills.js:2560:25)
    at http://localhost:3000/packs/polyfills.js:3688:37
    at HTMLCanvasElement.proto.(anonymous function) [as toBlob] (http://localhost:3000/packs/polyfills.js:3667:24)
    at http://localhost:3000/packs/application.js:33929:16
    at new ZoneAwarePromise (http://localhost:3000/packs/polyfills.js:3191:29)
    at canvasToBlob (http://localhost:3000/packs/application.js:33928:12)
```

I'm using Chrome 61, Zone.js 0.8.16, and Angular 4.4.6.

Should it be possible to use `canvas.toBlob` within a fakeAsync test? I can guess it may be fundamentally incompatible, requiring some kind of mocked `toBlob` backend similar to http requests, but it's hard to tell from the error message.

Thank you for a great product!

**Comment by JiaLiPassion** [comment]
@eric-simonton-sama , currently `fakeAsyncTest` does not support `canvas.toBlob`, I will try to make a PR to let `fakeAsyncTest` support it.
