### ISSUE TITLE
Inconsistency when importing zone.js in a project

### ISSUE THREAD

**Issue by jbgraug** [angular/zone.js#963]
Zone.js can be imported the lib in 2 ways...

1. require('zone.js');
2. require('zone.js/dist/zone.js');

The problem comes when a 3rd party lib is also importing zone.js in a different way than yours or than any other lib used in the project as it raises the **error** below:

How to solve this? 
Shouldn't ```require('zone.js')``` point to ```./dist/zone.js``` and for whoever wants to import the src use other formula like ```require('zone.js/src/lib/zone') ```or something similar?

```
Zone already loaded.
      at node_modules/zone.js/dist/zone-node.js:32:15
      at node_modules/zone.js/dist/zone-node.js:646:3
      at Object.<anonymous>.FUNCTION (node_modules/zone.js/dist/zone-node.js:9:65)
      at Object.<anonymous> (node_modules/zone.js/dist/zone-node.js:12:2)
```

**Comment by JiaLiPassion** [comment]
@jbgraug , zone.js will point to `dist/zone-node.js` when in nodejs environment. so your issue is 
one library `require('zone.js/dist/zone.js')` and  the other `require('zone.js/dist/zone-node.js')`?

**Comment by jbgraug** [comment]
Hi, could you elaborate more on this? I don't really understand the question.

**Comment by JiaLiPassion** [comment]
@jbgraug, maybe I didn't understand your case, could you post a sample repo to reproduce?

**Comment by jbgraug** [comment]
To reproduce just create a file with this content.
```
const zone = require('zone.js');
const zone2 = require('zone.js/dist/zone');
```
run it and you'll get 
```
node_modules/zone.js/dist/zone.js:32
        throw new Error('Zone already loaded.');
        ^
Error: Zone already loaded.
    at /Users/juangg/devel/training/package-testing/node_modules/zone.js/dist/zone.js:32:15
    at /Users/juangg/devel/training/package-testing/node_modules/zone.js/dist/zone.js:646:3
    at FUNCTION (/Users/juangg/devel/training/package-testing/node_modules/zone.js/dist/zone.js:9:65)
    at Object.<anonymous> (/Users/juangg/devel/training/package-testing/node_modules/zone.js/dist/zone.js:12:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
```
I know you would never do that... but when you use 3rd party libs that situation happens indirectly as other libs just import/require zone.js in different ways.

**Comment by JiaLiPassion** [comment]
@jbgraug , I see. 

```javascript
const zone = require('zone.js');
const zone2 = require('zone.js/dist/zone');
```

this is not the same, because `zone.js` need to support both `browser` and `nodejs` environment, 
`zone.js/dist/zone.js` means `browser`, and `zone.js/dist/zone-node.js` means `nodejs`.

so in `package.json`, the setting is 

```javascript
"main": "dist/zone-node.js",
 "browser": "dist/zone.js",
```

so it can handle both environments automatically.

**Comment by lyzJoey** [comment]
From my point, your problem is facing zone already loaded problem when importing 3rd party lib. Many people point out that angular zone should be loaded at last because angular needs zoneAwarePromise as the running zone(promise). If you load angular zone firstly, it will be override.

**Comment by exequielc** [comment]
I get this error whit Zone 0.8.21 
Error: Zone already loaded. 
  at http://localhost:8100/build/vendor.js:130606:15
    at http://localhost:8100/build/vendor.js:131218:3
    at FUNCTION (http://localhost:8100/build/vendor.js:130583:10)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:130586:2)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:133666:30)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.defineProperty.value (http://localhost:8100/build/vendor.js:81794:66)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:130101:72)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

**Comment by JiaLiPassion** [comment]
@exequielc , please post a reproduce repo, it seems you required `zone.js` twice.

**Comment by JiaLiPassion** [comment]
This should be ok for now. will close for now.
