### ISSUE TITLE
Angular5 - NullInjectorError: No provider for String! .

### ISSUE THREAD

**Issue by dhaniksahni** [angular/zone.js#974]
zone.js:693 Error: StaticInjectorError[String]: 
  StaticInjectorError[String]: 
    NullInjectorError: No provider for String!
    at _NullInjector.get (core.js:923)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveNgModuleDep (core.js:10585)
    at _createClass (core.js:10622)
    at _createProviderInstance$1 (core.js:10596)

Has anyone found this issue or Can anyone help on this?

**Comment by JiaLiPassion** [comment]
@dhaniksahni , I don't think this is a `zone.js` issue, you can also post it in `angular/angular` with a reproduce repo.

**Comment by KobbyMmo** [comment]
I had the same issue, but it turns out I had a string in my constructor and the injector service didn't know how to inject it

**Comment by tytskyi** [comment]
https://angular.io/guide/dependency-injection-in-action#injectiontoken

**Comment by baltzarmattsson** [comment]
My datasource service had a string in its constructor, previously used with @Inject(URL):

    constructor(
        @Inject(REST_URL)
        private url: string) {}


and changing to:

    private url: string;
    constructor() {
        this.url = environments.API_URL;
    }
   
solved it for me

**Comment by sharathc10** [comment]
did anyone figure this one out - i am getting a similar error when i run ng test on my cli project - i also have a string URL in my constructor:

`Error: StaticInjectorError[String]: 
  StaticInjectorError[String]: 
    NullInjectorError: No provider for String!
Error: StaticInjectorError[String]: 
  StaticInjectorError[String]: 
    NullInjectorError: No provider for String!
    at _NullInjector.webpackJsonp.../../../core/esm5/core.js._NullInjector.get (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:993:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:1281:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:1223:1)
    at StaticInjector.webpackJsonp.../../../core/esm5/core.js.StaticInjector.get (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:1094:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:1281:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:1223:1)
    at StaticInjector.webpackJsonp.../../../core/esm5/core.js.StaticInjector.get (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:1094:1)
    at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:10878:1)
    at _createClass (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:10917:1)
    at _createProviderInstance$1 (http://localhost:9876/_karma_webpack_/webpack:/Users/chitra/git/portal/portal-app/node_modules/@angular/core/esm5/core.js:10889:1)
`
 i i tried  the following in my spec file but it didn't work:

`providers: [ {provide: string, useValue: "stringValue"}],` 

I get a typescript error - string only refers to type but is being used as a value here 

any help is appreciated

**Comment by Woodsyla** [comment]
@sharathc10 you have used the String type therefore you need to provide that and not string

providers: [ {provide: String, useValue: "dummy"}],

I had same issue as op and this fixed my issue

**Comment by JiaLiPassion** [comment]
will close because not a zone.js issue.
